# Generated by Django 4.2.6 on 2023-10-28 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('alt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('alt_desc', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mod_name', models.CharField(max_length=250)),
                ('mod_desc', models.CharField(max_length=1000)),
                ('video', models.BinaryField(null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAPI.module')),
            ],
        ),
        migrations.CreateModel(
            name='Curse',
            fields=[
                ('curse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cur_name', models.CharField(max_length=250)),
                ('cur_desc', models.CharField(max_length=1000)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAPI.module')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAPI.alternative')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAPI.question')),
            ],
        ),
        migrations.AddField(
            model_name='alternative',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAPI.question'),
        ),
        migrations.CreateModel(
            name='ActiveCurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.CharField(max_length=1)),
                ('curse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAPI.curse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAPI.user')),
            ],
        ),
    ]
